// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScyFC8p80M3zfIH97HiWCCC__adUPtAo',
    appId: '1:1052131573052:web:087f91523042a109387239',
    messagingSenderId: '1052131573052',
    projectId: 'shawarmaoxa-pos',
    authDomain: 'shawarmaoxa-pos.firebaseapp.com',
    storageBucket: 'shawarmaoxa-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmEqME1fw3D0Bfab4CXQbQ0AVAVdfiz04',
    appId: '1:1052131573052:android:4c09638242d4d6aa387239',
    messagingSenderId: '1052131573052',
    projectId: 'shawarmaoxa-pos',
    storageBucket: 'shawarmaoxa-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoWzW7xQf1gvtv8E29h_oBGN2MXzp4qE',
    appId: '1:1052131573052:ios:14a73fec68f0b0e4387239',
    messagingSenderId: '1052131573052',
    projectId: 'shawarmaoxa-pos',
    storageBucket: 'shawarmaoxa-pos.firebasestorage.app',
    androidClientId: '1052131573052-dnrfgattri5q9227cl3tumft88u6idas.apps.googleusercontent.com',
    iosClientId: '1052131573052-ka0t98agf8ttcfeak24erbvjrp3scr80.apps.googleusercontent.com',
    iosBundleId: 'com.example.shawarmaPosNuevo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoWzW7xQf1gvtv8E29h_oBGN2MXzp4qE',
    appId: '1:1052131573052:ios:14a73fec68f0b0e4387239',
    messagingSenderId: '1052131573052',
    projectId: 'shawarmaoxa-pos',
    storageBucket: 'shawarmaoxa-pos.firebasestorage.app',
    androidClientId: '1052131573052-dnrfgattri5q9227cl3tumft88u6idas.apps.googleusercontent.com',
    iosClientId: '1052131573052-ka0t98agf8ttcfeak24erbvjrp3scr80.apps.googleusercontent.com',
    iosBundleId: 'com.example.shawarmaPosNuevo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCScyFC8p80M3zfIH97HiWCCC__adUPtAo',
    appId: '1:1052131573052:web:c431951245ccb0f6387239',
    messagingSenderId: '1052131573052',
    projectId: 'shawarmaoxa-pos',
    authDomain: 'shawarmaoxa-pos.firebaseapp.com',
    storageBucket: 'shawarmaoxa-pos.firebasestorage.app',
  );

}